# Dracula theme for walker 2.7+ with new format

[ui.window.box]
width = 800
min_width = 600
max_width = 1200
height = 500
min_height = 400
max_height = 600

[ui.window.box.scroll.list]
height = 400
min_height = 300
max_height = 500

[ui.window.box.scroll.list.item.icon]
pixel_size = 32

